---
services:
  # database
  mysql-db:
    image: mysql:8.0
    container_name: seated-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - seated-network

  redis:
    image: redis:7
    container_name: seated-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - seated-network

  # backend
  backend:
    build:
      context: ../backend/SeatedBackend/
      dockerfile: ../../docker/Dockerfile.backend.dev
    container_name: seated-backend-dev
    working_dir: /app
    volumes:
      - ../backend/SeatedBackend:/app
      - ~/.nuget/packages:/root/.nuget/packages
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:5165
      - ConnectionStrings__DefaultConnection=server=mysql-db;port=3306;database=${MYSQL_DATABASE};user=${MYSQL_USER};password=${MYSQL_PASSWORD}
      - ConnectionStrings__RedisConnection=redis:6379
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5165"]
    ports:
      - "5165:5165"
    depends_on:
      - mysql-db
      - redis
    networks:
      - seated-network

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: seated-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      PMA_HOST: mysql-db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql-db
    networks:
      - seated-network

volumes:
  mysql_data: {}

networks:
  seated-network: {}
