---
services:
  # database
  mysql-db:
    image: mysql:8.0
    container_name: seated-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - seated-network

  redis:
    image: redis:7
    container_name: seated-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - seated-network

  # python microservice
  nlp-service:
    build:
      context: ../nlp-service
      dockerfile: ../docker/Dockerfile.nlp
    container_name: seated-nlp
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ../nlp-service:/app
    networks:
      - seated-network
    environment:
      - HF_TOKEN=${HF_TOKEN}

  # backend
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: seated-backend
    restart: always
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:5165
      - ConnectionStrings__DefaultConnection=server=mysql-db;port=3306;database=${MYSQL_DATABASE};user=${MYSQL_USER};password=${MYSQL_PASSWORD}
      - ConnectionStrings__RedisConnection=redis:6379
    ports:
      - "5165:5165"
    depends_on:
      - mysql-db
      - redis
    networks:
      - seated-network

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: seated-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      PMA_HOST: mysql-db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql-db
    networks:
      - seated-network

volumes:
  mysql_data: {}

networks:
  seated-network: {}
